### ISSUE TITLE
Joining the team

### ISSUE THREAD

**Issue by 0x-r4bbit** [angular-translate/grunt-po2json-angular-translate#1]
Hey @DanielaValero this grunt plugin looks interesting! @firehist also implemented a grunt plugin for angular-translate. We're planning to move to an organization on github (http://github.com/angular-translate) there we also have a grunt-team which currently consists of @firehist only.

Maybe you're interested in joining the team as well? We would then put your grunt plugin under the organization umbrella :)

**Comment by DanielaValero** [comment]
Hi Pascal, 

That would be very nice, I'd be very glad to joining the team. 

Just let me know what's the next step and I'll collaborate with my best :D

**Comment by 0x-r4bbit** [comment]
@DanielaValero Wow that's awesome! For now you don't have to do anything. I'll just add you to our grunt team. When the time comes I'll ping you all guys anyway, since we have to move **all** angular-translate related projects to the organization.

I think it's great to have a team that takes care about specific grunt plugins :) I'm sure @firehist is with me.

So yea welcome! :)

**Comment by DanielaValero** [comment]
Super!!

I'm looking forward.

Regards!

**Comment by 0x-r4bbit** [comment]
@DanielaValero just made an announcement here: https://groups.google.com/forum/?hl=en-GB#!topic/angular-translate/jjaI3us5l10
